ALTER TABLE "Child" ADD COLUMN "specialPrizeRate" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Child" ADD COLUMN "firstPrizeRate" INTEGER NOT NULL DEFAULT 9;
ALTER TABLE "Child" ADD COLUMN "secondPrizeRate" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Child" ADD COLUMN "thirdPrizeRate" INTEGER NOT NULL DEFAULT 60;
